name: Scan Docker Image for Vulnerabilities TEST2

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'services/test2/**'
      - '.github/workflows/test2-build-image-scan.yaml'
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      test2: ${{ steps.filter.outputs.hit }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            hit:
              - 'services/test2/**'
              - '.github/workflows/test2-build-image-scan.yaml'
  build:
    runs-on: ubuntu-latest
    needs: [ changes ]
    if: needs.changes.outputs.hit == 'true' && github.event_name == 'pull_request'
    steps:
      - name: job b
        run: |
          echo "on Pull request hold for job B"
  scan:
    runs-on: ubuntu-latest
    needs: [ changes ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Require approvals before proceeding
        id: approvals
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: pr.base.repo.owner.login,
              repo: pr.base.repo.name,
              pull_number: pr.number,
              per_page: 200
            });
            // Count unique APPROVED reviewers (ignore dismissed)
            const approved = new Set(
              reviews.filter(r => r.state === 'APPROVED').map(r => r.user.login)
            );
            const REQUIRED = 1; // <-- change if you require 2+
            core.info(`Approvals: ${approved.size} (need ${REQUIRED})`);
            core.setOutput('ok', String(approved.size >= REQUIRED));

      - name: Stop until approved
        if: steps.approvals.outputs.ok != 'true'
        run: |
          echo "Not enough approvals yet; skipping scan."
          exit 0

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v3'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - id: 'sdk'
        name: setup gcloud SDK
        uses: 'google-github-actions/setup-gcloud@v3'

      - name: Read image destination from config.yaml
        id: read-destination
        run: |
          DEST=$(grep -- '--destination=' services/test2/config.yaml | sed 's/.*--destination="\{0,1\}\([^"]*\)"\{0,1\}.*/\1/')
          echo "📦 Destination found: $DEST"
          echo "DESTINATION=$DEST" >> $GITHUB_ENV

      - name: Scan image and show vulnerabilities
        id: scan
        run: |
          set -e
        
          IMAGE_URI="${DESTINATION}"
          echo "🔍 Scanning image: $IMAGE_URI"

          # Get image digest
          DIGEST=$(gcloud container images describe "$IMAGE_URI" --format='value(image_summary.digest)')
          IMAGE_URI_WITH_DIGEST="$IMAGE_URI@${DIGEST}"
          echo "Resolved Image: $IMAGE_URI_WITH_DIGEST"

          # Run on-demand vulnerability scan
          SCAN_NAME=$(gcloud artifacts docker images scan "$IMAGE_URI_WITH_DIGEST" \
            --remote --location=asia --format='value(response.scan)' --quiet)

          echo "Waiting for scan results..."
          gcloud artifacts docker images list-vulnerabilities "$SCAN_NAME" \
            --format=json > vuln-report.json
        
          echo "============================"
          echo "🧪 Vulnerability Summary"
          echo "============================"

          TOTAL=$(jq length vuln-report.json)
          CRITICAL=$(jq '[.[] | select(.vulnerability.effectiveSeverity=="CRITICAL")] | length' vuln-report.json)
          HIGH=$(jq '[.[] | select(.vulnerability.effectiveSeverity=="HIGH")] | length' vuln-report.json)
          MEDIUM=$(jq '[.[] | select(.vulnerability.effectiveSeverity=="MEDIUM")] | length' vuln-report.json)
          LOW=$(jq '[.[] | select(.vulnerability.effectiveSeverity=="LOW")] | length' vuln-report.json)

          echo "Total: $TOTAL"
          echo "Critical: $CRITICAL"
          echo "High: $HIGH"
          echo "Medium: $MEDIUM"
          echo "Low: $LOW"

          echo ""
          echo "============================"
          echo "📋 Top Vulnerabilities"
          echo "============================"
          jq -r '
            (if type == "array" then . else [.] end)
            | .[]
            | select(.vulnerability.effectiveSeverity == "HIGH" or .vulnerability.effectiveSeverity == "CRITICAL")
            | (.vulnerability.effectiveSeverity // "-") as $sev
            | (.vulnerability.shortDescription // (.noteName | tostring | split("/") | last) // "-") as $id
            | (.vulnerability.packageIssue // [])[0] as $pi
            | [
                $sev,
                $id,
                ($pi.affectedPackage // "-"),
                ($pi.affectedVersion.fullName // "-"),
                ($pi.fixedVersion.fullName // "-"),
                ($pi.packageType // "-"),
                (((.vulnerability.relatedUrls // []) | map(.url) | first) // "-")
              ]
            | @tsv
          ' vuln-report.json |
          awk -F'\t' 'BEGIN {
            printf "%-8s | %-16s | %-28s | %-14s | %-14s | %-6s | %s\n",
            "SEV","CVE/ID","PACKAGE","AFFECTED","FIXED","TYPE","URL"
            printf "--------|------------------|------------------------------|----------------|----------------|--------|----------------------------------------\n"
          }
          { printf "%-8s | %-16s | %-28s | %-14s | %-14s | %-6s | %s\n",$1,$2,$3,$4,$5,$6,$7 }
          { printf "--------|------------------|------------------------------|----------------|----------------|--------|----------------------------------------\n"}' 
          echo "CRITICAL=$CRITICAL" >> $GITHUB_ENV
          echo "HIGH=$HIGH" >> $GITHUB_ENV
          echo "IMAGE_URI_WITH_DIGEST=$IMAGE_URI_WITH_DIGEST" >> $GITHUB_ENV

          if [[ "$CRITICAL" -gt 0 || "$HIGH" -gt 0 ]]; then
            echo "❌ Found high/critical vulnerabilities!"
            exit 1
          else
            echo "✅ No high or critical vulnerabilities found."
          fi
